version: "3.8"
services:
  frontend:
    build: ./warehouse-front
    ports:
    - 80:80
  backend:
    container_name: back
    build: ./warehouse-back
    ports: 
      - '8060:8060' 
    restart: on-failure
    depends_on:
      - fullstack-postgres
    networks:
      - fullstack
  fullstack-postgres:
    image: postgres:latest
    container_name: warehouse-pg
    environment:
      - POSTGRES_USER=ensler
      - POSTGRES_PASSWORD=b4uld103
    ports:
      - '5435:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - fullstack
  click-db:
    image: yandex/clickhouse-server
    container_name: warehouse-click
    networks:
      - fullstack
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - database_click:/var/lib/postgresql/data
volumes:
  database_postgres:
  database_click:

networks:
  fullstack:
    driver: bridge