version: "3.8"
services:
  frontend:
    build: ./warehouse-front
    ports:
    - 80:80
  backend:
    container_name: back
    build: ./warehouse-back
    ports: 
      - 8060:8060 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - fullstack-postgres
    networks:
      - fullstack
  fullstack-postgres:
    image: postgres:latest
    container_name: full_db_postgres
    environment:
      - POSTGRES_USER=ensler
      - POSTGRES_PASSWORD=b4uld103
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - fullstack
volumes:
  api:
  database_postgres:

networks:
  fullstack:
    driver: bridge